---
- hosts: all
  become: true

  pre_tasks:
    - name: Perform apt update
      apt: update_cache=true

    - name: Perform apt upgrade
      apt: upgrade=yes

    - name: Install Python packages & git
      apt: 
        name:
          - python3
          - python3-pip
          - python3-venv
          - pipx
          - git
        state: present
    
    - name: Install python-poetry
      shell: |
        pipx install poetry
      become_user: vagrant
    
    - name: Clone fetchai/uAgents Github repo
      git: 
        repo: https://github.com/fetchai/uAgents.git
        dest: /vagrant/opt/uAgents
        force: yes
    
  tasks:
    
    - name: Install uAgents framework
      shell: |
        pipx ensurepath
        export PATH=$PATH:/home/vagrant/.local/bin
        source /etc/profile 
        poetry init
        poetry install
      args:
        chdir: /vagrant/opt/uAgents/python
        executable: /bin/bash
      become_user: vagrant

    - name: Install Poetry shell plugin
      shell: |
        export PATH=$PATH:/home/vagrant/.local/bin
        source /etc/profile 
        pipx inject poetry poetry-plugin-shell
      args:
        chdir: /vagrant/opt/uAgents/python
        executable: /bin/bash
      become_user: vagrant

    - name: Installation Success Message

